//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteKunstenboetiek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactuurRegel
    {
        public int RegelNr { get; set; }
        public int FactuurNr { get; set; }
        public int ArtikelNr { get; set; }
    
        public virtual Artikel Artikel { get; set; }
        public virtual Factuur Factuur { get; set; }
    }
}
